USE BOOTCAMP;
SELECT * FROM ANIMALS ORDER BY id DESC;
SELECT * FROM ANIMALS WHERE weight > 30 ORDER BY id;
SELECT * FROM ANIMALS WHERE name LIKE "L%" ORDER BY id;
SELECT * FROM ANIMALS GROUP BY species ORDER BY id DESC;
SELECT * FROM ANIMALS WHERE weight > 100 GROUP BY species ORDER BY id;